Writable:
  LogLevel: INFO
  Telemetry:
    Interval: 30s

Service:
  Host: localhost
  Port: 59790 # Adjust if running multiple examples at the same time to avoid duplicate port conflicts
  StartupMsg: LF Edge IotDB Export Service

MessageBus:
  Disabled: false # Set to true if not using edgex-messagebus Trigger below and Metrics are not enabled
  Optional:
    ClientId: app-iotdb-export

IotDBConfig:
  Host: localhost
  Port: '6667'
  UserName: root
  Password: root
  FetchSize: 1024
  TimeZone: UTC
  ConnectRetryMax: 5
  RPCCompression: false
  ConnectionTimeout: 5
  Prefix: ""

